Repository young2866/logEat, pull requests merged in 2024-02, with the labels that each got.

#11 공통 예외처리 핸들러 작성
  src/main/java/com/encore/logeat/common/exception/GlobalException.java
Labels: 🍀코드리뷰

#9 유저 일반 회원가입
  .gitignore
  build.gradle
  src/main/java/com/encore/logeat/common/dto/ResponseDto.java
  src/main/java/com/encore/logeat/common/jwt/JwtTokenProvider.java
  src/main/java/com/encore/logeat/common/security/SecurityConfig.java
  src/main/java/com/encore/logeat/user/controller/UserController.java
  src/main/java/com/encore/logeat/user/domain/User.java
  src/main/java/com/encore/logeat/user/dto/request/UserCreateRequestDto.java
  src/main/java/com/encore/logeat/user/dto/request/UserLoginRequestDto.java
  src/main/java/com/encore/logeat/user/repository/UserRepository.java
  src/main/java/com/encore/logeat/user/service/UserService.java
  src/main/resources/application.yml
Labels: 🍀코드리뷰

#17 Post create
  src/main/java/com/encore/logeat/common/dto/ResponseDto.java
  src/main/java/com/encore/logeat/post/Dto/PostCreateRequestDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/domain/Post.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
Labels: 🍀코드리뷰

#16 [feat] 엔티티 연관관계 수정
  src/main/java/com/encore/logeat/follow/domain/Follow.java
  src/main/java/com/encore/logeat/like/domain/Like.java
  src/main/java/com/encore/logeat/post/domain/Post.java
  src/main/java/com/encore/logeat/user/domain/User.java
Labels: 🍀코드리뷰

#22 [feat] JWT Filter 구현
  src/main/java/com/encore/logeat/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/encore/logeat/common/jwt/JwtTokenProvider.java
  src/main/java/com/encore/logeat/common/security/SecurityConfig.java
  src/main/java/com/encore/logeat/follow/domain/Follow.java
  src/main/java/com/encore/logeat/user/controller/UserController.java
  src/main/java/com/encore/logeat/user/service/UserService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#23 글 검색
  src/main/java/com/encore/logeat/post/Dto/RequestDto/PostCreateRequestDto.java
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostSearchResponseDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#24 유저 로그인시 Refresh Token 발급
  src/main/java/com/encore/logeat/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/encore/logeat/common/jwt/JwtTokenProvider.java
  src/main/java/com/encore/logeat/common/jwt/refresh/UserRefreshToken.java
  src/main/java/com/encore/logeat/common/jwt/refresh/UserRefreshTokenRepository.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/user/service/UserService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#28 회원가입시 이메일 인증 구현
  build.gradle
  src/main/java/com/encore/logeat/common/redis/RedisConfig.java
  src/main/java/com/encore/logeat/common/redis/RedisService.java
  src/main/java/com/encore/logeat/mail/controller/MailController.java
  src/main/java/com/encore/logeat/mail/service/EmailService.java
  src/main/java/com/encore/logeat/user/service/UserService.java
  src/test/java/com/encore/logeat/junstin/EmailServiceTest.java
  src/test/java/com/encore/logeat/junstin/EmailTest.java
  src/test/java/com/encore/logeat/junstin/RedisTest.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#29 글 좋아요 기능
  src/main/java/com/encore/logeat/common/dto/ResponseDto.java
  src/main/java/com/encore/logeat/like/Repository/LikeRepository.java
  src/main/java/com/encore/logeat/like/controller/LikeController.java
  src/main/java/com/encore/logeat/like/domain/Like.java
  src/main/java/com/encore/logeat/like/service/LikeService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#35 게시글 수정
  build.gradle
  settings.gradle
  src/main/java/com/encore/logeat/like/domain/Like.java
  src/main/java/com/encore/logeat/post/Dto/RequestDto/PostUpdateRequestDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/domain/Post.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#33 게시글 삭제
  build.gradle
  src/main/java/com/encore/logeat/mail/service/EmailService.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#30 비밀번호 변경
  src/main/java/com/encore/logeat/common/exception/GlobalException.java
  src/main/java/com/encore/logeat/mail/controller/MailController.java
  src/main/java/com/encore/logeat/mail/service/EmailService.java
  src/main/java/com/encore/logeat/user/domain/User.java
  src/main/java/com/encore/logeat/user/service/UserService.java
  src/test/java/com/encore/logeat/junstin/EmailServiceTest.java
  src/test/java/com/encore/logeat/junstin/UpdatedPasswordTest.java
Labels: 🍀코드리뷰

#39 글 조회 및 좋아요 수정
  src/main/java/com/encore/logeat/like/domain/Like.java
  src/main/java/com/encore/logeat/like/service/LikeService.java
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostSearchResponseDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/domain/Post.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
  src/main/java/com/encore/logeat/user/service/UserService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#41 유저 팔로우 기능 구현
  src/main/java/com/encore/logeat/follow/controller/FollowController.java
  src/main/java/com/encore/logeat/follow/domain/Follow.java
  src/main/java/com/encore/logeat/follow/repository/FollowRepository.java
  src/main/java/com/encore/logeat/follow/service/FollowService.java
  src/main/java/com/encore/logeat/user/controller/UserController.java
  src/main/java/com/encore/logeat/user/service/UserService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#42 [feat]게시글 상세보기
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostDetailResponseDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#38 비공개 글 작성
  src/main/java/com/encore/logeat/post/Dto/RequestDto/PostSecretUpdateRequestDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/domain/Post.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#53 [feat] 주간, 월간 좋아요 상위글 표시
  src/main/java/com/encore/logeat/like/service/LikeService.java
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostLikeMonthResponseDto.java
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostLikeWeekResponseDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/domain/PostLikeReport.java
  src/main/java/com/encore/logeat/post/repository/PostLikeReportRepository.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
  src/test/java/com/encore/logeat/junstin/MonthPostReadTest.java
  src/test/java/com/encore/logeat/junstin/UpdatedPasswordTest.java
Labels: 🍀코드리뷰

#46 [feat] 팔로우한 유저의 최신 글
  src/main/java/com/encore/logeat/follow/repository/FollowRepository.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
  src/main/java/com/encore/logeat/user/repository/UserRepository.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#51 [feat]mypage 보기 및 수정 기능
  src/main/java/com/encore/logeat/user/controller/UserController.java
  src/main/java/com/encore/logeat/user/domain/User.java
  src/main/java/com/encore/logeat/user/dto/request/UserInfoResponseDto.java
  src/main/java/com/encore/logeat/user/dto/request/UserInfoUpdateRequestDto.java
  src/main/java/com/encore/logeat/user/dto/request/UserLoginRequestDto.java
  src/main/java/com/encore/logeat/user/service/UserService.java
Labels: 🔼백엔드-개발

#55 [feat] 주간, 월간 좋아요 상위 리스트 구현
  src/main/java/com/encore/logeat/like/service/LikeService.java
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostLikeMonthResponseDto.java
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostLikeWeekResponseDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/domain/PostLikeReport.java
  src/main/java/com/encore/logeat/post/repository/PostLikeReportRepository.java
  src/test/java/com/encore/logeat/junstin/MonthPostReadTest.java
  src/test/java/com/encore/logeat/junstin/UpdatedPasswordTest.java
Labels: 🍀코드리뷰

#56 [feat]글 작성시 팔로워들에게 알림 기능 구현
  src/main/java/com/encore/logeat/notification/controller/NotificationController.java
  src/main/java/com/encore/logeat/notification/domain/Notification.java
  src/main/java/com/encore/logeat/notification/domain/NotificationType.java
  src/main/java/com/encore/logeat/notification/dto/request/NotificationCreateDto.java
  src/main/java/com/encore/logeat/notification/dto/response/NotificationListResponseDto.java
  src/main/java/com/encore/logeat/notification/repository/NotificationRepository.java
  src/main/java/com/encore/logeat/notification/service/NotificationService.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/user/domain/User.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#49 [feat] 게시글 상세조회 캐싱 기능 구현
  src/main/java/com/encore/logeat/LogeatApplication.java
  src/main/java/com/encore/logeat/common/redis/CacheNames.java
  src/main/java/com/encore/logeat/common/redis/RedisConfig.java
  src/main/java/com/encore/logeat/common/redis/RedisService.java
  src/main/java/com/encore/logeat/like/service/LikeService.java
  src/main/java/com/encore/logeat/post/Dto/ResponseDto/PostDetailResponseDto.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/domain/Post.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#58 유저 회원가입
  src/main/java/com/encore/logeat/common/security/SecurityConfig.java
  src/main/java/com/encore/logeat/user/controller/UserController.java
  src/main/java/com/encore/logeat/user/repository/UserRepository.java
  src/main/java/com/encore/logeat/user/service/UserService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#59 [feat] 글 작성시 이미지 S3에 저장하는 기능 구현
  build.gradle
  src/main/java/com/encore/logeat/common/s3/S3Config.java
  src/main/java/com/encore/logeat/common/security/SecurityConfig.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/user/controller/UserController.java
Labels: ⏫프론트-개발, 🔼백엔드-개발, 🍀코드리뷰

#60 [feat] 메일 서비스 기능 테스트
  src/main/java/com/encore/logeat/mail/EmailAuthService.java
  src/main/java/com/encore/logeat/mail/EmailAuthServiceImpl.java
  src/main/java/com/encore/logeat/mail/EmailConfig.java
  src/main/java/com/encore/logeat/mail/service/EmailService.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
Labels: 🍀코드리뷰, ✅테스트

#64 [feat]mypost
  src/main/java/com/encore/logeat/like/domain/Like.java
  src/main/java/com/encore/logeat/like/service/LikeService.java
  src/main/java/com/encore/logeat/post/Service/PostService.java
  src/main/java/com/encore/logeat/post/controller/PostController.java
  src/main/java/com/encore/logeat/post/repository/PostRepository.java
Labels: 🔼백엔드-개발
